config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'
  devise_for :users, skip: :registration
  as :user do
    get 'users', to: 'dashboard#index', as: :user_root
    get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
    patch 'users', to: 'devise/registrations#update', as: 'user_registration'
  end

  resources :dashboard, only: [:index]
  resources :events, only: [:index, :show, :new, :create]
  resources :restaurants, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :dishes, only: [:create, :destroy]

  get '/company/events', to: 'events#company_index'
  get '/get_rest_dishes', to: 'events#get_rest_dishes'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :departments
  has_many :users

  has_many :company_restaurants, dependent: :destroy
  has_many :restaurants, through: :company_restaurants
end

app/models/company_restaurant.rb
class CompanyRestaurant < ActiveRecord::Base
  belongs_to :company
  belongs_to :restaurant
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :company
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :dish_category
  belongs_to :restaurant

  has_many :dish_images, dependent: :destroy

  validates :name, :price, presence: true
  validates :dish_category, presence: true

  def create_dish_image(image)
    dish_images.create(image: image)
  end
end

app/models/dish_category.rb
class DishCategory < ActiveRecord::Base
  has_many :dishes
end

app/models/dish_image.rb
class DishImage < ActiveRecord::Base
  belongs_to :dish

  has_attached_file :image, styles: { medium: "800x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :restaurant
  has_many :users, through: :event_people
  has_many :event_people, dependent: :destroy
  has_many :dishes, through: :event_dishes
  has_many :event_dishes, dependent: :destroy

  validates :date, presence: true
  validates :restaurant_id, presence: true

  scope :by_month, -> (date) { where(date: month_duration(date)) }
  scope :by_category, -> (rc_id) { where(restaurants: { restaurant_category_id: rc_id }) }

  def self.company_events(user)
    colleagues = User.colleagues(user.company_id)

    joins(:users)
    .includes(:restaurant)
    .where(event_people: { user_id: colleagues })
    .distinct
  end

  def self.company_events_on_condition(user, rc_id, month)
    unless rc_id
      company_events(user)
      .by_month(month_to_date(month))
    else
      company_events(user)
      .by_category(rc_id)
      .by_month(month_to_date(month))
    end
  end

  def self.my_events(user)
    joins(:users)
    .includes(:restaurant)
    .where(event_people: { user_id: user.id })
    .distinct
  end

  def self.my_events_on_condition(user, rc_id, month)
    unless rc_id
      my_events(user)
      .by_month(month_to_date(month))
    else
      my_events(user)
      .by_category(rc_id)
      .by_month(month_to_date(month))
    end
  end

  def self.month_duration(date)
    date.beginning_of_month..date.end_of_month
  end

  def self.month_to_date(month)
    Date.today.change(month: month.to_i)
  end

  def add_participants(participants)
    users << participants
  end

  def add_dishes(our_dishes)
    dishes << our_dishes
  end
end

app/models/event_dish.rb
class EventDish < ActiveRecord::Base
  belongs_to :event
  belongs_to :dish
end

app/models/event_person.rb
class EventPerson < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :events, dependent: :destroy
  has_many :dishes, dependent: :destroy
  belongs_to :restaurant_category

  has_many :company_restaurants, dependent: :destroy
  has_many :companies, through: :company_restaurants

  validates :name, :address, :phone_number, presence: true
  validates_format_of :phone_number, with: /0[2-8]\d{7,8}\z/i
  validates :restaurant_category_id, presence: true

  def self.by_company(company_id)
    joins(:companies)
    .where(company_restaurants: { company_id: company_id })
  end

  def add_company(company)
    companies << company
  end
end

app/models/restaurant_category.rb
class RestaurantCategory < ActiveRecord::Base
  has_many :restaurants
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :company
  belongs_to :department
  has_many :events, through: :event_people
  has_many :event_people

  def full_name
    "#{first_name} #{last_name}"
  end

  def chinese_full_name
    "#{chinese_last_name}#{chinese_first_name}"
  end

  def self.colleagues(company_id)
    where(company_id: company_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      unless @dish.save && upload_image
        format.js { flash.now[:notice] = 'error' }
      end
      format.js
    end
  end

  def destroy
    @dish = Dish.find(params[:id])
    @err_msg = nil

    respond_to do |format|
      if @dish.destroy
        format.js
      else
        @err_msg = t('views.actions.destroy_error')
        format.js
      end
    end
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :price, :dish_category_id, :restaurant_id)
  end

  def upload_image
    @dish.create_dish_image(params[:dish][:image])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ParamValidator

  def index
    month = get_month
    page = get_page
    restaurant_category_id = get_restaurant_category_id

    @events = Event.my_events_on_condition(
      current_user,
      restaurant_category_id,
      month
    ).page(page)
  end

  def company_index
    month = get_month
    page = get_page
    restaurant_category_id = get_restaurant_category_id

    @events = Event.company_events_on_condition(
      current_user,
      restaurant_category_id,
      month
    ).page(page)
  end

  def show
    @event = Event.includes(:users).find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    if make_event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def get_rest_dishes
    @dishes = Dish.where(restaurant_id: params[:restaurant_id])
  end

  private

  def event_params
    params.require(:event).permit(:date, :restaurant_id)
  end

  def make_event
    event = Event.new(event_params)
    event.add_participants(param_users)
    event.add_dishes(param_dishes)
    event
  end

  def param_dishes
    Dish.where(id: params[:dish][:ids])
  end

  def param_users
    User.where(id: params[:users][:user_ids])
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_filter :authenticate_user!, only: :index
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "success"
    when "error" then "danger"
    when "alert" then "warning"
    end
  end

  def on_events_page?
    if params[:controller] == 'events'
      true
    else
      false
    end
  end

  def on_restaurants_page?
    if params[:controller] == 'restaurants'
      true
    else
      false
    end
  end

  def avatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def join_users(users)
    users.map(&:full_name).join(", ")
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
  def dish_categories
    DishCategory.all.map do |dish|
      [dish.name, dish.id]
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def selected_month
    params[:month] ? params[:month].to_i : Date.today
  end

  def selected_category
    params[:category] ? params[:category].to_i : nil
  end

  def restaurants
    Restaurant.all.map do |restaurant|
      [restaurant.name, restaurant.id]
    end
  end

  def colleagues
    User.colleagues(current_user.company_id)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def restaurant_categories
    RestaurantCategory.all.map do |category|
      [category.name, category.id]
    end
  end

  def id_param
    params[:id]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lunch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <%= render 'shared/navbar' %>
  <% else %>
    <%= render 'shared/landing_navbar' %>
  <% end %>

  <div class="container">
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </div>

  <% if params[:controller] == 'landing' %>
  <% else %>
    <%= render 'shared/footer' %>
  <% end %>
</body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= flash_class(key) %> alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">&copy 2016. Made with <i class="fa fa-heart" aria-hidden="true"></i> by tonyhsu23</p>
  </div>
</footer>

app/views/shared/_landing_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Lunch Schedule', root_path, { class: 'navbar-brand' } %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('devise.login.title'), new_user_session_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Lunch Schedule', dashboard_index_path, { class: 'navbar-brand' } %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown <%= 'active' if on_events_page? %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t('activerecord.models.event') %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('views.navbar.new_event'), new_event_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to t('views.navbar.my_event'), events_path %></li>
            <li><%= link_to t('views.navbar.company_event'), company_events_path %></li>
          </ul>
        </li>
        <li class="<%= 'active' if on_restaurants_page? %>">
          <%= link_to t('activerecord.models.restaurant'), restaurants_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="avatar dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag avatar_url(current_user, '38') %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"><%= link_to current_user.chinese_full_name, edit_user_registration_path %></a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>