config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#index'
  devise_for :users, skip: :registration
  as :user do
    get 'users', to: 'dashboard#index', as: :user_root
    get 'users/edit', to: 'devise/registrations#edit', as: 'edit_user_registration'
    patch 'users', to: 'devise/registrations#update', as: 'user_registration'
  end

  resources :dashboard, only: [:index]
  resources :events, only: [:index, :show, :new, :create]
  resources :restaurants, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :dishes, only: [:create, :destroy]

  get '/company/events', to: 'events#company_index'
  get '/get_rest_dishes', to: 'events#get_rest_dishes'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :events, dependent: :destroy
  has_many :dishes, dependent: :destroy
  belongs_to :restaurant_category

  has_many :company_restaurants, dependent: :destroy
  has_many :companies, through: :company_restaurants

  validates :name, :address, :phone_number, presence: true
  validates_format_of :phone_number, with: /0[2-8]\d{7,8}\z/i
  validates :restaurant_category_id, presence: true

  def self.by_company(company_id)
    joins(:companies)
    .where(company_restaurants: { company_id: company_id })
  end

  def add_company(company)
    companies << company
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.by_company(current_user.company.id)
    @restaurant = Restaurant.new
  end

  def show
    @restaurant = find_restaurant
    @dishes = @restaurant.dishes.includes(:dish_category, :dish_images)
    @dish = Dish.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.add_company(current_user.company)

    respond_to do |format|
      unless @restaurant.save
        format.js { flash.now[:notice] = 'error' }
      end
      format.js
    end
  end

  def edit
    @restaurant = find_restaurant
  end

  def update
    @restaurant = find_restaurant
    if @restaurant.update(restaurant_params)
      redirect_to restaurants_path,
        flash: { notice: t('activerecord.update_success') }
    else
      render :edit
    end
  end

  def destroy
    @restaurant = find_restaurant
    if @restaurant.destroy
      redirect_to restaurants_path,
        flash: { notice: t('activerecord.destroy_success') }
    else
      render :edit
    end
  end

  private

  def find_restaurant
    Restaurant.find(params[:id])
  end
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :restaurant_category_id)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def restaurant_categories
    RestaurantCategory.all.map do |category|
      [category.name, category.id]
    end
  end

  def id_param
    params[:id]
  end
end

app/views/restaurants/_restaurant.html.erb
<hr>
<h3><%= restaurant.name %></h3>
<h5><%= fa_icon 'phone' %> <%= restaurant.phone_number %></h5>
<h5><%= fa_icon 'map-marker' %> <%= restaurant.address %></h5>
<%= link_to(t('views.content.menu'), restaurant, class: 'btn btn-primary') %>
<%= link_to(t('activerecord.edit'), edit_restaurant_path(restaurant), class: 'btn btn-success') %>

app/views/restaurants/create.js.erb
$(".restaurant-block").append("<%= j(render @restaurant) %>");
$(".flash").html("<%= flash[:notice] %>");
$(".new_restaurant")[0].reset();

app/views/restaurants/edit.html.erb
<div class="col-md-4 col-md-offset-4" >
  <div class="flash"></div>
  <h2><%= t('activerecord.edit') + @restaurant.model_name.human %></h2>
  <%= form_for @restaurant, validate: true do |f| %>
    <div class="field form-group">
      <%= f.select :restaurant_category_id,
        restaurant_categories, { include_blank: t('views.placeholder.restaurant.select_category') }, { class: 'form-control', required: true } %>
  </div>

  <div class="field form-group">
    <%= f.text_field :name, { class: 'form-control', required: true, placeholder: t('views.placeholder.restaurant.name', default: 'Name') } %>
  </div>

  <div class="field form-group">
    <%= f.text_field :address, { class: 'form-control', required: true, placeholder: t('views.placeholder.restaurant.address', default: 'Address') } %>
  </div>

  <div class="field form-group">
    <%= f.telephone_field :phone_number, { class: 'form-control', required: true, placeholder: t('views.placeholder.restaurant.phone', default: 'Phone Number') } %>
  </div>

  <div class="field form-group">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to t('activerecord.cancel'), restaurants_path, class: 'btn btn-default' %>
    <%= link_to t('activerecord.delete'), @restaurant, method: :delete, data: { confirm: t('views.actions.destroy_confirm') }, class: 'btn btn-danger pull-right' %>
  </div>
<% end %>
</div>

app/views/restaurants/index.html.erb
<div class="row">
  <div class="col-md-9">
    <h1><%= Restaurant.model_name.human %></h1>
    <div id="restaurants" class="restaurant-block">
      <%= div_for @restaurants do |restaurant|  %>
        <%= render restaurant %>
      <% end %>
    </div>
  </div>

  <div class="col-md-3 <%= controller_name %>-<%= action_name %>" >
    <div class="flash"></div>
    <h2><%= t("views.actions.new_restaurant") %></h2>
    <%= form_for @restaurant, validate: true, remote: true do |f| %>
      <div class="field form-group">
        <%= f.select :restaurant_category_id,
          restaurant_categories, { include_blank: t('views.placeholder.restaurant.select_category') }, { class: 'form-control', required: true } %>
      </div>

      <div class="field form-group">
        <%= f.text_field :name, { class: 'form-control', required: true, placeholder: t('views.placeholder.restaurant.name', default: 'Name') } %>
      </div>

      <div class="field form-group">
        <%= f.text_field :address, { class: 'form-control', required: true, placeholder: t('views.placeholder.restaurant.address', default: 'Address') } %>
      </div>

      <div class="field form-group">
        <%= f.telephone_field :phone_number, { class: 'form-control', required: true, placeholder: t('views.placeholder.restaurant.phone', default: 'Phone Number') } %>
      </div>

      <div class="field form-group">
        <%= f.submit class: 'btn btn-primary form-control' %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to Restaurant.model_name.human, restaurants_path %></li>
  <li class="active"><%= @restaurant.name %></li>
</ol>

<div class="flash"></div>
<h2><%= @restaurant.name %></h2>

<h4><%= t("views.actions.new_dish") %></h4>
<%= form_for @dish, { multipart: true, remote: true } do |f| %>
  <div class="form-inline">
    <div class="field form-group">
      <%= f.select :dish_category_id,
        dish_categories, { include_blank: t('views.placeholder.dish.select_category') }, { class: 'form-control', required: true } %>
    </div>

    <div class="field form-group">
      <%= f.text_field :name,
        { class: 'form-control', placeholder: t('views.placeholder.dish.name', default: 'Name'), required: true} %>
    </div>

    <div class="field form-group">
      <%= f.number_field :price,
        { class: 'form-control', placeholder: t('views.placeholder.dish.price', default: 'Price'), required: true } %>
    </div>

    <div class="field form-group">
      <%= f.label t('views.placeholder.dish.upload') %>
      <%= f.file_field :image %>
    </div>

    <div class="field form-group">
      <%= f.hidden_field(:restaurant_id, value: id_param) %>
      <%= f.submit class: 'btn btn-primary fomr-control' %>
    </div>
  </div>
<% end %>

<br>

<div class="row">
  <div class="col-lg-12">
    <h4><%= t('views.content.menu') %></h4>
  </div>
</div>

<div class="row text-center dish-block">
  <%= div_for @dishes do |dish| %>
    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <% unless dish.dish_images.empty? %>
          <%= image_tag dish.dish_images.first.image.url %>
        <% else %>
          <img src="http://placehold.it/800x500" alt="">
        <% end %>
        <div class="caption">
          <h3><%= dish.name %></h3>
          <p>NTD <%= dish.price %></p>
        </div>
        <%= link_to dish, method: :delete, remote: true, data: { confirm: t('views.actions.destroy_confirm') } do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
    <%# <%= render dish %1> %>
  <% end %>
</div>